# Generated by Django 6.1 on 2026-09-05 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agentic_django", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("session",),
                name="agent_run_one_running_session",
            ),
        ),
    ]
